
import React, { useMemo, useState } from 'react';

const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const parties=[
 {name:'Labour Party',short:'Labour',leader:'Keir Starmer',colour:'#dc2626',seats:280,approval:42,unity:68},
 {name:'Conservative Party',short:'Conservative',leader:'Kemi Badenoch',colour:'#2563eb',seats:170,approval:34,unity:58},
 {name:'Reform UK',short:'Reform',leader:'Nigel Farage',colour:'#06b6d4',seats:45,approval:28,unity:74},
 {name:'Liberal Democrats',short:'Lib Dems',leader:'Ed Davey',colour:'#eab308',seats:55,approval:31,unity:70},
 {name:'Green Party',short:'Green',leader:'Zack Polanski',colour:'#16a34a',seats:12,approval:22,unity:76},
 {name:'SNP',short:'SNP',leader:'John Swinney',colour:'#f59e0b',seats:35,approval:24,unity:62},
];
const manifestoAreas=['Economy','NHS','Immigration','Housing','Welfare','Climate','Crime','Foreign Policy','Education'];
const regions=['London','South East','South West','Midlands','North West','North East','Yorkshire','Wales','Scotland','Northern Ireland'];
const sampleSeats=['Aldridge-Brownhills','Birmingham Ladywood','Clacton','Uxbridge and South Ruislip','Bristol Central','Islington North','Cardiff North','Glasgow South','Belfast East','Nuneaton','Guildford','Wrexham','Tamworth','Blackpool South','Mid Bedfordshire','Selby and Ainsty'];
const shadowCabinets={
 Labour:['Keir Starmer','Rachel Reeves','Yvette Cooper','Wes Streeting','David Lammy'],
 Conservative:['Kemi Badenoch','Mel Stride','Chris Philp','Priti Patel','Laura Trott'],
 Reform:['Nigel Farage','Richard Tice','Lee Anderson','Reform Health Team'],
 'Lib Dems':['Ed Davey','Daisy Cooper','Sarah Olney','Munira Wilson'],
 Green:['Zack Polanski','Carla Denyer','Adrian Ramsay','Ellie Chowns'],
 SNP:['John Swinney','Stephen Flynn','Kirsty Blackman','Pete Wishart']
};
const ministerTraits=['Loyalist','Ambitious','Media Darling','Technocrat','Backstabber','Scandal Magnet','Ideologue','Ruthless Operator','Incompetent','Party Fixer'];
const cabinetRoles=['Chancellor','Home Secretary','Foreign Secretary','Health Secretary','Education Secretary','Defence Secretary','Housing Secretary','Justice Secretary'];
const cobra=[
 {title:'NHS ransomware attack',threat:'CRITICAL',text:'Hospitals report cancelled operations and inaccessible records.',options:['Deploy military cyber units','Bring in private contractors','Blame hostile state','Minimise issue']},
 {title:'London terror incident',threat:'SEVERE',text:'Met Police report a coordinated incident in central London.',options:['Deploy armed police','Authorise MI5 raids','National address','Wait for more information']},
 {title:'Gilt market panic',threat:'ECONOMIC CRISIS',text:'Borrowing costs spike after markets question fiscal plans.',options:['Fiscal stability statement','Reverse costly pledge','Attack speculators','Delay response']},
 {title:'Channel crossings surge',threat:'POLITICAL CRISIS',text:'A sudden rise in Channel crossings dominates the news agenda.',options:['UK-France command centre','Military patrols','Increase asylum processing','Blame France']}
];
const summits=[
 {title:'NATO Emergency Summit',leaders:['US President','French President','German Chancellor','NATO Secretary General'],options:['Push troop deployment','Sanctions only','De-escalation diplomacy']},
 {title:'G7 Economic Summit',leaders:['US President','Canadian PM','French President','Japanese PM'],options:['Champion free trade','Protect UK industry','Independent UK line']},
 {title:'COP Climate Summit',leaders:['UN Climate Chair','EU President','US President','Indian PM'],options:['Aggressive green pledges','Balanced commitments','Delay costly promises']}
];
function makeMinisters(party){return cabinetRoles.map((r,i)=>({role:r,name:(party.short==='Labour'?['Rachel Reeves','Yvette Cooper','David Lammy','Wes Streeting','Bridget Phillipson','John Healey','Lisa Nandy','Shabana Mahmood'][i]:party.short==='Conservative'?['Mel Stride','Chris Philp','Priti Patel','Edward Argar','Laura Trott','Tom Tugendhat','Robert Jenrick','Victoria Atkins'][i]:`${party.short} Minister ${i+1}`),competence:clamp(45+(i*13)%50,35,95),loyalty:clamp(42+(i*17)%52,20,95),ambition:clamp(30+(i*19)%60,10,95),trait:ministerTraits[(i*3+party.short.length)%ministerTraits.length]}))}
function judge(text){const t=text.toLowerCase();let ap=1, cost=0, centre=0, risk='Balanced'; if(/tax cut|cut tax|lower tax/.test(t)){ap+=2;cost+=5;centre-=1;risk='Popular but fiscally risky'} if(/nhs|nurse|doctor|hospital/.test(t)){ap+=3;cost+=4} if(/border|immigration|deport|asylum/.test(t)){ap+=2;centre+=1} if(/green|climate|energy/.test(t)){ap+=1;cost+=2} if(/funded|costed|efficiency|reduce waste/.test(t)){ap+=2;cost-=3;centre+=3;risk='Credible and costed'} if(text.length<25){ap-=2;risk='Too vague'} return {approval:clamp(ap,-5,8),cost:clamp(cost,-5,10),centre,risk};}
function App(){
 const [game,setGame]=useState({screen:'start',party:null,phase:'manifesto',week:4,approval:40,unity:60,seats:0,inflation:4.8,deficit:62,market:50,leadership:12,manifesto:{},log:['Choose a party to begin.'],cabinet:[],headline:'Election campaign begins',declared:0,scenario:null});
 const poll=useMemo(()=>clamp(Math.round(game.approval*.55+game.unity*.25-game.inflation*1.2),5,55),[game]);
 const projected=useMemo(()=>game.party?clamp(Math.round(game.party.seats+(poll-38)*4.5),1,390):0,[game.party,poll]);
 const update=(patch,msg)=>setGame(g=>({...g,...patch,log:msg?[msg,...g.log].slice(0,8):g.log,headline:msg||g.headline}));
 if(game.screen==='start')return <div className="app"><Hero/><div className="cards">{parties.map(p=><button className="party" onClick={()=>setGame({...game,screen:'play',party:p,approval:p.approval,unity:p.unity,seats:p.seats,cabinet:makeMinisters(p),manifesto:Object.fromEntries(manifestoAreas.map(a=>[a,''])),headline:`${p.name} manifesto drafting`,log:[`You are leading ${p.name}. Build your manifesto.`]})} key={p.short} style={{'--c':p.colour}}><div className="stripe"/><h2>{p.name}</h2><p>Leader: {p.leader}</p><b>{p.seats} starting seats</b></button>)}</div></div>;
 return <div className="app play"><Ticker game={game} poll={poll} projected={projected}/><header><div><small>{game.party.short} · {game.phase}</small><h1>Fantasy Parliament Simulator</h1></div><button onClick={()=>location.reload()}>Restart</button></header><div className="grid"><aside><Stats game={game} poll={poll} projected={projected}/><Panel title="Latest movement">{game.log.map((l,i)=><p className="log" key={i}>{l}</p>)}</Panel></aside><main><Decision game={game} update={update} setGame={setGame} projected={projected}/></main></div></div>
}
function Hero(){return <section className="hero"><span>READY TO DEPLOY</span><h1>Fantasy Parliament Simulator</h1><p>A UK politics strategy game with elections, Parliament, cabinet drama, COBRA crises, by-elections, diplomacy, summits and constituency results.</p></section>}
function Stats({game,poll,projected}){return <Panel title="Dashboard"><div className="stats"><Mini l="Approval" v={game.approval+'%'}/><Mini l="Poll" v={poll+'%'}/><Mini l="Seats" v={game.seats||projected}/><Mini l="Inflation" v={game.inflation+'%'}/><Mini l="Deficit" v={'£'+game.deficit+'bn'}/><Mini l="Leadership threat" v={game.leadership+'%'}/></div></Panel>}
function Decision({game,update,setGame,projected}){
 if(game.phase==='manifesto')return <Manifesto game={game} setGame={setGame} update={update}/>;
 if(game.phase==='campaign')return <Campaign game={game} update={update} projected={projected}/>;
 if(game.phase==='election')return <ElectionNight game={game} setGame={setGame} projected={projected}/>;
 if(game.phase==='cabinet')return <Cabinet game={game} update={update}/>;
 if(game.phase==='government')return <Government game={game} update={update} setGame={setGame}/>;
 if(game.phase==='parliament')return <Parliament game={game} update={update}/>;
 if(game.phase==='cobra')return <Cobra game={game} update={update}/>;
 if(game.phase==='byelection')return <ByElection game={game} update={update}/>;
 if(game.phase==='summit')return <Summit game={game} update={update}/>;
 if(game.phase==='map')return <Map game={game} update={update}/>;
 return null;
}
function Manifesto({game,setGame,update}){const filled=Object.values(game.manifesto).filter(Boolean).length; return <Panel title="Custom Manifesto Builder"><p>Type your own policies before the election. The simulator judges credibility and cost.</p>{manifestoAreas.map(a=>{const val=game.manifesto[a]||'';const j=val?judge(val):null;return <div className="field" key={a}><label>{a}</label><textarea value={val} onChange={e=>setGame(g=>({...g,manifesto:{...g.manifesto,[a]:e.target.value}}))} placeholder={`Type your ${a} policy...`}/>{j&&<small>{j.risk} · approval {j.approval>0?'+':''}{j.approval} · fiscal pressure {j.cost>0?'+':''}{j.cost}</small>}</div>})}<button disabled={filled<3} onClick={()=>update({phase:'campaign',approval:clamp(game.approval+2,5,80)},'Manifesto launched. Campaign begins.')}>Launch manifesto</button></Panel>}
function Campaign({game,update,projected}){return <Panel title={`Election Campaign: ${game.week} weeks left`}><p>Campaign before election night. Opposition AI reacts every week.</p><div className="actions"><button onClick={()=>update({approval:clamp(game.approval+2,5,80),week:game.week-1},'Economy-first campaign dominates the news.')}>Economy campaign</button><button onClick={()=>update({approval:clamp(game.approval+3,5,80),week:game.week-1},'NHS rescue message lands well.')}>NHS campaign</button><button onClick={()=>update({approval:clamp(game.approval+1,5,80),week:game.week-1},'TV leaders debate creates viral clips.')}>TV debate</button><button onClick={()=>update({approval:clamp(game.approval-1,5,80),week:game.week-1},'Opposition AI launches a sharp attack.')}>Advance week</button></div>{game.week<=1&&<button className="primary" onClick={()=>update({phase:'election',seats:projected,declared:12},'BBC exit poll released.')}>Go to Election Night</button>}</Panel>}
function ElectionNight({game,setGame,projected}){const seats=sampleSeats.concat(Array.from({length:80},(_,i)=>`Constituency ${i+1}`));const shown=seats.slice(0,game.declared);return <Panel title="Election Night"><h2>{game.party.name}: projected {projected} seats</h2><div className="tiles">{shown.map((s,i)=><span title={s} className={(i*37)%100 < projected/650*100?'tile ours':'tile opp'} key={s}/>)}</div><div className="results">{shown.slice(-8).reverse().map((s,i)=><p key={i}><b>{s}</b> declares: {(i+game.declared)%3?'HOLD':'GAIN'}</p>)}</div>{game.declared<seats.length?<button onClick={()=>setGame(g=>({...g,declared:clamp(g.declared+12,0,seats.length)}))}>Next declarations</button>:<button onClick={()=>setGame(g=>({...g,phase:projected>=270?'cabinet':'government',seats:projected,headline:'Final result declared'}))}>Continue</button>}</Panel>}
function Cabinet({game,update}){return <Panel title="Cabinet Formation"><p>Ministers have competence, loyalty, ambition and personality traits.</p>{game.cabinet.map(m=><div className="minister" key={m.role}><b>{m.role}</b><span>{m.name}</span><small>Competence {m.competence}% · Loyalty {m.loyalty}% · Ambition {m.ambition}% · {m.trait}</small></div>)}<button onClick={()=>update({phase:'government'},'Cabinet appointed. Government begins.')}>Begin Government</button></Panel>}
function Government({game,update,setGame}){return <Panel title="Government Command Centre"><div className="actions"><button onClick={()=>update({phase:'parliament',scenario:{bill:'Government Reform Bill',stage:0,controversy:35}},'Government Reform Bill introduced.')}>Introduce Bill</button><button onClick={()=>setGame(g=>({...g,phase:'cobra',scenario:cobra[Math.floor(Math.random()*cobra.length)]}))}>Activate COBRA</button><button onClick={()=>setGame(g=>({...g,phase:'byelection',scenario:{seat:sampleSeats[Math.floor(Math.random()*sampleSeats.length)],pressure:45+Math.floor(Math.random()*30)}}))}>Trigger By-election</button><button onClick={()=>setGame(g=>({...g,phase:'summit',scenario:summits[Math.floor(Math.random()*summits.length)]}))}>Trigger Global Summit</button><button onClick={()=>update({phase:'map'},'Election HQ opened.')}>Interactive UK Map</button><button onClick={()=>update({leadership:clamp(game.leadership+15,0,100)},'Backbench leadership rumours intensify.')}>Leadership challenge pressure</button></div><Shadow game={game}/></Panel>}
function Parliament({game,update}){const stages=['First Reading','Second Reading','Committee Stage','Select Committee Evidence','Report Stage','Third Reading','House of Lords','Commons Ping-Pong','Royal Assent'];const s=game.scenario;return <Panel title="Westminster Parliament"><h2>{s.bill}</h2><p>Stage: {stages[s.stage]}</p><div className="stats"><Mini l="Expected Ayes" v={Math.max(250,game.seats-Math.round(s.controversy))}/><Mini l="Expected Noes" v={650-game.seats+Math.round(s.controversy/2)}/><Mini l="Controversy" v={s.controversy+'%'}/></div><div className="actions"><button onClick={()=>update({scenario:{...s,controversy:clamp(s.controversy-8,0,100)}},'Amendments offered to reduce rebellion risk.')}>Offer amendments</button><button onClick={()=>update({unity:clamp(game.unity-3,0,100),scenario:{...s,controversy:clamp(s.controversy+4,0,100)}},'Hard three-line whip imposed.')}>Three-line whip</button><button onClick={()=>update({scenario:{...s,controversy:clamp(s.controversy-5,0,100)}},'Select committee evidence improves credibility.')}>Committee evidence</button></div><button onClick={()=> s.stage>=stages.length-1?update({phase:'government',approval:clamp(game.approval+2,5,80)},`${s.bill} receives Royal Assent.`):update({scenario:{...s,stage:s.stage+1}},`${s.bill} advances to ${stages[s.stage+1]}.`)}>Advance stage</button></Panel>}
function Cobra({game,update}){const c=game.scenario;return <Panel title="COBRA Emergency Room"><h2>{c.title}</h2><b>Threat level: {c.threat}</b><p>{c.text}</p><div className="actions">{c.options.map((o,i)=><button key={o} onClick={()=>update({phase:'government',approval:clamp(game.approval+(i===0?4:i===3?-5:2),5,80),leadership:clamp(game.leadership+(i===3?10:-3),0,100)},`COBRA decision: ${o}`)}>{o}</button>)}</div></Panel>}
function ByElection({game,update}){const b=game.scenario;return <Panel title="By-election"><h2>{b.seat}</h2><p>Pressure level: {b.pressure}%</p><div className="actions">{['Send PM','Send star minister','Local spending promise','Attack campaign','Ignore'].map((o,i)=><button key={o} onClick={()=>update({phase:'government',approval:clamp(game.approval+(i<3?2:-4),5,80),leadership:clamp(game.leadership+(i===4?10:-4),0,100)},`By-election result after strategy: ${o}`)}>{o}</button>)}</div></Panel>}
function Summit({game,update}){const s=game.scenario;return <Panel title="Global Summit"><h2>{s.title}</h2><p>Attending: {s.leaders.join(', ')}</p><div className="actions">{s.options.map((o,i)=><button onClick={()=>update({phase:'government',market:clamp(game.market+(i===0?3:i===1?-2:2),0,100)},`${s.title}: ${o}`)} key={o}>{o}</button>)}</div></Panel>}
function Map({game,update}){return <Panel title="Interactive UK Constituency Map"><p>Clickable seat grid for election HQ. Use it to target campaign pushes.</p><div className="seatgrid">{sampleSeats.concat(Array.from({length:120},(_,i)=>`Seat ${i+1}`)).map((s,i)=><button key={s} title={s} onClick={()=>update({approval:clamp(game.approval+1,5,80)},`Targeted campaign launched in ${s}.`)} className={(i%6===0?'cyan':i%5===0?'yellow':i%4===0?'green':'blue')}>{i+1}</button>)}</div></Panel>}
function Shadow({game}){const opp=game.party.short==='Labour'?'Conservative':'Labour';return <div className="shadow"><h3>Opposition Watch: {opp}</h3>{(shadowCabinets[opp]||[]).map(x=><span key={x}>{x}</span>)}</div>}
function Ticker({game,poll,projected}){const texts=[`BBC POLITICS: ${game.headline}`,`POLL: ${game.party?.short||'Party'} on ${poll}% and ${projected} projected seats`,`FT: Markets at ${game.market}% confidence`,`SKY: Leadership threat ${game.leadership}%`];return <div className="ticker"><div>{texts.concat(texts).map((t,i)=><span key={i}>{t}</span>)}</div></div>}
function Panel({title,children}){return <section className="panel"><h1>{title}</h1>{children}</section>}
function Mini({l,v}){return <div className="mini"><small>{l}</small><b>{v}</b></div>}
export default App;
