import React, { useMemo, useState } from 'react';
import { Home, Users, FileText, Globe2, Grid2X2, Search } from 'lucide-react';

const clamp = (n,min,max)=>Math.max(min,Math.min(max,n));

const parties = [
  { name:'Labour Party', short:'Labour', colour:'red', leader:'Keir Starmer', stats:{approval:52,seats:285,unity:68,left:65,centre:54,right:24}},
  { name:'Conservative Party', short:'Conservative', colour:'blue', leader:'Kemi Badenoch', stats:{approval:39,seats:190,unity:58,left:18,centre:42,right:65}},
  { name:'Reform UK', short:'Reform', colour:'cyan', leader:'Nigel Farage', stats:{approval:31,seats:65,unity:74,left:8,centre:30,right:78}},
  { name:'Liberal Democrats', short:'Lib Dems', colour:'yellow', leader:'Ed Davey', stats:{approval:34,seats:72,unity:72,left:43,centre:63,right:24}},
  { name:'Green Party', short:'Green', colour:'green', leader:'Zack Polanski', stats:{approval:26,seats:16,unity:76,left:70,centre:37,right:8}},
];

const manifestoAreas = ['Economy','NHS','Immigration','Housing','Welfare','Climate','Crime','Foreign Policy','Education'];
const regions = ['Scotland','North East','North West','Yorkshire','Midlands','Wales','London','South East','South West','Northern Ireland'];
const opponents = {
  Labour:['Keir Starmer','Rachel Reeves','Yvette Cooper','Wes Streeting','David Lammy','Bridget Phillipson'],
  Conservative:['Kemi Badenoch','Mel Stride','Chris Philp','Priti Patel','Laura Trott','Victoria Atkins'],
  Reform:['Nigel Farage','Richard Tice','Lee Anderson','Reform Health Team'],
  'Lib Dems':['Ed Davey','Daisy Cooper','Munira Wilson','Sarah Olney'],
  Green:['Zack Polanski','Carla Denyer','Adrian Ramsay','Ellie Chowns']
};
const cabinetPool = ['Rachel Reeves','Angela Rayner','Yvette Cooper','David Lammy','Wes Streeting','Ed Miliband','Shabana Mahmood','Pat McFadden','John Healey','Bridget Phillipson','Robert Jenrick','James Cleverly','Priti Patel','Mel Stride','Chris Philp','Victoria Atkins','Tom Tugendhat','Jeremy Hunt'];
const cabinetRoles = ['Chancellor','Home Secretary','Foreign Secretary','Health Secretary','Education Secretary','Defence Secretary','Housing Secretary','Work & Pensions','Climate Secretary','Justice Secretary'];
const traits = ['Loyalist','Ambitious','Media Darling','Technocrat','Backstabber','Scandal Magnet','Ideologue','Ruthless Operator','Pragmatist','Party Fixer'];
const summitPool = [
  {title:'NATO Emergency Summit', leaders:['US President','French President','German Chancellor','Polish PM','NATO Secretary General'], opts:['Push troop deployment','Sanctions only','De-escalation diplomacy']},
  {title:'G7 Economic Summit', leaders:['US President','Canadian PM','French President','German Chancellor','Japanese PM'], opts:['Champion free trade','Protect UK industry','Independent UK line']},
  {title:'COP Climate Summit', leaders:['UN Climate Chair','EU President','US President','Indian PM'], opts:['Aggressive green pledges','Balanced commitments','Delay costly commitments']},
];
const cobraPool = [
  {title:'London terror incident', threat:'SEVERE', advice:['Home Secretary: armed policing surge','MI5: immediate raids','Defence: military support ready','Cabinet Office: address the nation'], opts:['Deploy armed police','Authorise MI5 raids','National address','Wait for more information']},
  {title:'NHS ransomware attack', threat:'CRITICAL', advice:['Health Secretary: emergency funding','NCSC: hostile actor likely','Chancellor: markets nervous','NHS England: systems failing'], opts:['Military cyber units','Private contractors','Blame hostile state','Minimise panic']},
  {title:'Gilt market panic', threat:'ECONOMIC CRISIS', advice:['Chancellor: fiscal statement needed','Bank: credibility required','Markets: demand stability','Chief Whip: MPs panicking'], opts:['Fiscal stability statement','Reverse costly pledge','Attack speculators','Delay response']},
  {title:'Severe nationwide flooding', threat:'MAJOR INCIDENT', advice:['Defence: army rescue units','Treasury: emergency grants','Environment Agency: more rain','Councils: urgent support'], opts:['Army rescue + grants','PM visit','Flood defence review','Leave to councils']},
];
const debateQs = [
  ['Economy','How will you bring inflation under control while supporting growth?'],
  ['NHS','How will you reduce NHS waiting lists without reckless spending?'],
  ['Immigration','How will you control immigration and borders?'],
  ['Crime','What is your plan to make communities safer?'],
  ['Climate','Can Britain realistically afford climate commitments?']
];
const seats = Array.from({length:650},(_,i)=>({name:['Birmingham Ladywood','Clacton','Uxbridge','Islington North','Putney','Cardiff North','Glasgow South','Belfast East','Dudley','Nuneaton'][i%10] + (i>9?` ${i}`:''), nation: regions[i%regions.length], x: 5 + ((i*37)%90), y: 5 + ((i*61)%86), electorate: 62000 + ((i*913)%32000)}));

function judge(text, area){
  const t=text.toLowerCase(); let approval=1, deficit=0, inflation=0, verdict='Balanced but needs detail';
  if(t.includes('tax cut')||t.includes('spending')||t.includes('free')){approval+=2;deficit+=5; inflation+=0.2; verdict='Popular but fiscally risky'}
  if(t.includes('funded')||t.includes('fiscal')||t.includes('targeted')||t.includes('efficiency')){approval+=3;deficit-=3; inflation-=0.1; verdict='Credible and costed'}
  if(t.includes('nhs')||area==='NHS') approval+=2;
  if(t.includes('border')||t.includes('police')||t.includes('crime')) approval+=1;
  if(text.length<35){approval-=2; verdict='Too vague — media will demand detail'}
  return {approval:clamp(approval,-5,8), deficit:clamp(deficit,-5,8), inflation:Number(inflation.toFixed(1)), verdict};
}

const base = {screen:'select', tab:'home', phase:'manifesto', party:null, approval:52,poll:39,seats:285,inflation:4.8,deficit:62,market:50,unity:68,leadership:12,manifesto:{}, manifestoResult:null, week:4, headline:'Election campaign begins', log:['Welcome to Number 10.'], cabinet:{}, bill:null, cobra:null, byelection:null, summit:null, debate:null, electionDeclared:18, social:['#BritainVotes trending','#PMQs live','#Westminster'], mapSearch:'', regionSupport:Object.fromEntries(regions.map(r=>[r,50]))};

export default function App(){
  const [s,setS]=useState(base);
  const update=(patch)=>setS(p=>({...p,...patch}));
  const polling = clamp(Math.round((s.approval*.45+s.unity*.25+s.market*.15+s.poll*.15)-(s.inflation-3)*1.3),5,55);
  const projected = clamp(Math.round(s.seats+(polling-38)*4.4),1,390);
  if(s.screen==='select') return <PartySelect setS={setS}/>;
  return <Shell s={s} setS={setS} update={update} polling={polling} projected={projected}/>;
}

function PartySelect({setS}){return <div className="selectPage"><div className="hero"><span>PREMIUM CAMPAIGN MODE</span><h1>Fantasy Parliament Simulator</h1><p>Choose a party, build a manifesto, fight an election, govern through crises and survive Westminster.</p></div><div className="partyGrid">{parties.map(p=><button className={`party ${p.colour}`} key={p.name} onClick={()=>setS({...base,screen:'game',party:p,approval:p.stats.approval,seats:p.stats.seats,unity:p.stats.unity,poll:39,manifesto:Object.fromEntries(manifestoAreas.map(a=>[a,''])),headline:`${p.name} manifesto drafting begins`})}><div className="stripe"/><h2>{p.name}</h2><p>Leader: {p.leader}</p><p>{p.stats.seats} starting seats · unity {p.stats.unity}%</p></button>)}</div></div>}

function Shell({s,setS,update,polling,projected}){const nav=[['home',Home],['cabinet',Users],['papers',FileText],['world',Globe2],['more',Grid2X2]];return <div className="app"><div className="glow"/><main><div className="topbar"><b>21:32</b><span className="pillDot"/><b>▮▮▮ Wi‑Fi 37</b></div><header><div className="kicker">{s.party.short} · {s.phase.includes('campaign')?'CAMPAIGN':'GOVERNMENT'}</div><h1>Zeeshan Kamran⌄</h1><button onClick={()=>setS(base)}>Restart</button></header><div className="breaking"><b>BREAKING</b><span>{s.headline}</span><em>• now</em></div>{s.tab==='home'&&<HomePanel s={s} setS={setS} update={update} polling={polling} projected={projected}/>} {s.tab==='cabinet'&&<CabinetPanel s={s} setS={setS}/>} {s.tab==='papers'&&<PapersPanel s={s} setS={setS}/>} {s.tab==='world'&&<WorldPanel s={s} setS={setS}/>} {s.tab==='more'&&<MorePanel s={s} setS={setS}/>}<Ticker s={s} polling={polling} projected={projected}/><nav>{nav.map(([id,Icon])=><button className={s.tab===id?'active':''} key={id} onClick={()=>update({tab:id})}><Icon size={22}/><small>{id[0].toUpperCase()+id.slice(1)}</small></button>)}</nav></main></div>}

function HomePanel({s,setS,update,polling,projected}){return <div className="layout"><aside><Card title="Dashboard"><div className="statGrid"><Stat k="Approval" v={`${s.approval}%`}/><Stat k="Poll" v={`${polling}%`}/><Stat k="Seats" v={s.seats||projected}/><Stat k="Inflation" v={`${s.inflation}%`}/><Stat k="Deficit" v={`£${s.deficit}bn`}/><Stat k="Leadership" v={`${s.leadership}%`}/></div></Card><Card title="Latest movement">{s.log.slice(0,5).map((l,i)=><p className="log" key={i}>{l}</p>)}</Card></aside><section><Card title="Decision Room"><Phase s={s} setS={setS} update={update} polling={polling} projected={projected}/></Card></section></div>}

function Phase({s,setS,update,polling,projected}){
  if(s.phase==='manifesto') return <Manifesto s={s} setS={setS}/>;
  if(s.phase==='campaign') return <Campaign s={s} setS={setS} projected={projected}/>;
  if(s.phase==='debate') return <Debate s={s} setS={setS}/>;
  if(s.phase==='electionNight') return <ElectionNight s={s} setS={setS} projected={projected}/>;
  if(s.phase==='cabinet') return <CabinetBuilder s={s} setS={setS}/>;
  if(s.phase==='bill') return <Bill s={s} setS={setS}/>;
  if(s.phase==='cobra') return <Cobra s={s} setS={setS}/>;
  if(s.phase==='byelection') return <ByElection s={s} setS={setS}/>;
  if(s.phase==='summit') return <Summit s={s} setS={setS}/>;
  if(s.phase==='map') return <MapExplorer s={s} setS={setS}/>;
  return <GovCentre s={s} setS={setS}/>;
}

function GovCentre({s,setS}){return <><Section kicker="Government" title="Government Command Centre" sub="Run Parliament, emergencies, diplomacy, by-elections and leadership survival."/><div className="actions"><Btn onClick={()=>setS(p=>({...p,phase:'bill',bill:{name:'Government Reform Bill',stage:0,controversy:38,rebels:22,amends:[]},headline:'Government Reform Bill introduced'}))}>Introduce Bill</Btn><Btn onClick={()=>setS(p=>({...p,phase:'cobra',cobra:cobraPool[Math.floor(Math.random()*cobraPool.length)],headline:'COBRA activated'}))}>Activate COBRA</Btn><Btn onClick={()=>setS(p=>({...p,phase:'byelection',byelection:seats[Math.floor(Math.random()*650)],headline:'By-election called'}))}>Trigger By-election</Btn><Btn onClick={()=>setS(p=>({...p,phase:'summit',summit:summitPool[Math.floor(Math.random()*summitPool.length)],headline:'Global summit begins'}))}>Trigger Global Summit</Btn><Btn onClick={()=>setS(p=>({...p,phase:'map'}))}>Interactive UK Map</Btn><Btn onClick={()=>setS(p=>({...p,leadership:clamp(p.leadership+18,0,100),headline:'Leadership challenge pressure rises',log:['Backbench MPs are discussing letters of no confidence.',...p.log]}))}>Leadership challenge pressure</Btn></div><Opposition s={s}/></>}

function Manifesto({s,setS}){const filled=manifestoAreas.filter(a=>s.manifesto[a]?.trim()).length; const total=manifestoAreas.reduce((a,k)=>a+(s.manifesto[k]?judge(s.manifesto[k],k).approval:0),0);return <><Section kicker="Manifesto Builder" title={`${s.party.name} Manifesto`} sub="Type your own policies. The simulator judges cost, credibility and voter appeal."/><div className="miniRow"><Stat k="Written" v={`${filled}/9`}/><Stat k="Potential" v={total>0?`+${total}`:total}/><Stat k="Readiness" v={filled>=5?'Ready':'Thin'}/></div><div className="manifestoGrid">{manifestoAreas.map(a=><div className="policyBox" key={a}><b>{a}</b><textarea value={s.manifesto[a]||''} onChange={e=>setS(p=>({...p,manifesto:{...p.manifesto,[a]:e.target.value}}))} placeholder={`Type your ${a} policy...`}/>{s.manifesto[a]&&<small>{judge(s.manifesto[a],a).verdict}</small>}</div>)}</div><button className="primary" disabled={filled<3} onClick={()=>setS(p=>({...p,phase:'campaign',approval:clamp(p.approval+Math.round(total/4),5,80),headline:'Manifesto launched',log:[`Manifesto launched with ${filled} policy areas.`,...p.log]}))}>Launch Manifesto</button></>}

function Campaign({s,setS,projected}){return <><Section kicker={`Campaign Week ${s.week}`} title="Election Campaign HQ" sub="Campaign nationally, launch debate moments and fight for a majority."/><div className="miniRow"><Stat k="Projected seats" v={projected}/><Stat k="Weeks left" v={s.week}/><Stat k="Online trend" v={s.social[0]}/></div><div className="actions"><Btn onClick={()=>setS(p=>({...p,approval:clamp(p.approval+2,5,80),headline:'NHS campaign push dominates headlines',log:['Campaign focus: NHS waiting lists.',...p.log]}))}>Campaign on NHS</Btn><Btn onClick={()=>setS(p=>({...p,approval:clamp(p.approval+1,5,80),market:clamp(p.market+4,0,100),headline:'Economy-first campaign launched',log:['Campaign focus: fiscal credibility.',...p.log]}))}>Campaign on Economy</Btn><Btn onClick={()=>setS(p=>({...p,phase:'debate',debate:{round:0,score:0},headline:'BBC Leaders Debate begins'}))}>BBC Leaders Debate</Btn><Btn onClick={()=>setS(p=>p.week>1?({...p,week:p.week-1,headline:`Campaign week ${p.week-1} begins`,log:[`Campaign week advanced.`,...p.log]}):({...p,phase:'electionNight',seats:projected,electionDeclared:18,headline:'BBC exit poll released'}))}>Advance Campaign</Btn></div></>}

function Debate({s,setS}){const [topic,q]=debateQs[s.debate.round]||debateQs[0];const answers={Economy:['Fiscal discipline with targeted investment','Attack opposition borrowing','Pivot to growth and wages'],NHS:['Expand evening/weekend appointments','Fix social care discharge delays','Recruit and retain NHS staff'],Immigration:['Speed asylum decisions','Break trafficking gangs','Firm borders and fair rules'],Crime:['Neighbourhood policing','Faster courts for victims','Target repeat offenders'],Climate:['Clean power and lower bills','Green jobs plan','Protect consumers during transition']};return <><Section kicker="BBC Leaders’ Debate Live" title={`Round ${s.debate.round+1}: ${topic}`} sub={q}/><div className="debateBox"><Stat k="Audience" v={`${clamp(50+s.debate.score*4,10,90)}%`}/><Stat k="Social buzz" v="71%"/><Stat k="Score" v={s.debate.score}/></div><div className="actions">{answers[topic].map((a,i)=><Btn key={a} onClick={()=>setS(p=>{const next=p.debate.round+1; if(next>=debateQs.length) return {...p,phase:'campaign',approval:clamp(p.approval+p.debate.score+2,5,80),headline:'Debate night concludes',log:['Debate completed. Media reaction floods in.',...p.log]}; return {...p,debate:{round:next,score:p.debate.score+i+2},headline:`Opponent challenges your ${topic} answer`,log:[`Debate answer: ${a}`,...p.log]}})}>{a}</Btn>)}</div></>}

function ElectionNight({s,setS,projected}){const declared=seats.slice(0,s.electionDeclared);const won=declared.filter((_,i)=>i%3!==0).length;return <><Section kicker="Election Night" title="Constituency declarations coming in" sub={`${s.party.name} projected on ${s.seats || projected} seats.`}/><div className="miniRow"><Stat k="Declared" v={`${declared.length}/650`}/><Stat k={s.party.short} v={won}/><Stat k="Opposition" v={declared.length-won}/></div><div className="tileBoard">{declared.map((seat,i)=><span key={i} title={seat.name} className={i%3===0?'opp':'you'}/>)}</div><div className="declarations">{declared.slice(-8).reverse().map((seat,i)=><p key={i}><b>{seat.name}</b> — {i%3===0?'Opposition gain':`${s.party.short} hold`} · Swing +{i+2}</p>)}</div><button className="primary" onClick={()=>s.electionDeclared<650?setS(p=>({...p,electionDeclared:clamp(p.electionDeclared+40,0,650)})):setS(p=>({...p,phase:'cabinet',headline:'Election result confirmed'}))}>{s.electionDeclared<650?'Continue Declarations':'Form Government'}</button></>}

function CabinetBuilder({s,setS}){const filled=Object.keys(s.cabinet).length;return <><Section kicker="Form Government" title="Appoint your Cabinet" sub="Choose ministers based on expertise, popularity, loyalty and risk."/><div className="cabinetGrid">{cabinetRoles.map((r,i)=><div className="policyBox" key={r}><b>{r}</b><select value={s.cabinet[r]?.name||''} onChange={e=>{const mp={name:e.target.value,expertise:r,loyalty:40+((i*13)%55),competence:50+((i*17)%45),popularity:35+((i*19)%60),traits:[traits[i%traits.length],traits[(i+3)%traits.length]]}; setS(p=>({...p,cabinet:{...p.cabinet,[r]:mp}}))}}><option value="">Select MP</option>{cabinetPool.map(n=><option key={n}>{n}</option>)}</select>{s.cabinet[r]&&<small>{s.cabinet[r].traits.join(' · ')}</small>}</div>)}</div><button className="primary" disabled={filled<5} onClick={()=>setS(p=>({...p,phase:'government',headline:'Cabinet appointed',log:[`Cabinet appointed: ${filled}/10 roles filled.`,...p.log]}))}>Begin Government</button></>}

function CabinetPanel({s,setS}){return <Panel title="Cabinet">{Object.entries(s.cabinet).length?Object.entries(s.cabinet).map(([r,m])=><div className="minister" key={r}><b>{r}</b><h3>{m.name}</h3><div className="miniRow"><Stat k="Loyalty" v={`${m.loyalty}%`}/><Stat k="Competence" v={`${m.competence}%`}/><Stat k="Popularity" v={`${m.popularity}%`}/></div><p>{m.traits.join(' · ')}</p></div>):<p>Appoint your cabinet after election night.</p>}</Panel>}

function PapersPanel({s,setS}){return <Panel title="Papers & Parliament"><Phase s={s} setS={setS}/></Panel>}
function WorldPanel({s,setS}){return <Panel title="Foreign Affairs"><div className="actions"><Btn onClick={()=>setS(p=>({...p,headline:'Secure line opened with United States',log:['Call with US President on NATO, trade and China.',...p.log]}))}>Call United States</Btn><Btn onClick={()=>setS(p=>({...p,headline:'EU trade talks begin',log:['EU negotiations opened on trade and migration.',...p.log]}))}>EU Talks</Btn><Btn onClick={()=>setS(p=>({...p,market:clamp(p.market+3,0,100),headline:'India trade deal talks advance',log:['FTA negotiations with India progress.',...p.log]}))}>India Trade Deal</Btn><Btn onClick={()=>setS(p=>({...p,phase:'summit',summit:summitPool[Math.floor(Math.random()*summitPool.length)]}))}>Global Summit</Btn></div></Panel>}
function MorePanel({s,setS}){return <Panel title="More"><div className="actions"><Btn onClick={()=>setS(p=>({...p,phase:'map',tab:'home'}))}>Election HQ / Map</Btn><Btn onClick={()=>setS(p=>({...p,phase:'debate',tab:'home',debate:{round:0,score:0}}))}>TV Debate</Btn><Btn onClick={()=>setS(p=>({...p,headline:'Party conference opens',log:['Annual party conference begins.',...p.log]}))}>Party Conference</Btn><Btn onClick={()=>setS(p=>({...p,headline:'Social media command opened',social:['#PMStatement','#Westminster','#PoliticsLive']}))}>Social Media Hub</Btn></div></Panel>}

function Bill({s,setS}){const stages=['First Reading','Second Reading','Committee','Select Committee','Report','Third Reading','Lords','Commons Ping-Pong','Royal Assent'];const b=s.bill;return <><Section kicker="Westminster Parliament" title={b.name} sub={`${stages[b.stage]} · Rebels expected: ${b.rebels}`}/><div className="miniRow"><Stat k="Ayes" v={clamp(s.seats-b.rebels,0,650)}/><Stat k="Noes" v={650-s.seats+b.rebels}/><Stat k="Controversy" v={`${b.controversy}%`}/></div><div className="actions"><Btn onClick={()=>setS(p=>({...p,bill:{...p.bill,amends:[...p.bill.amends,'Offer amendments'],controversy:clamp(p.bill.controversy-8,0,100)},headline:'Government offers amendments'}))}>Offer amendments</Btn><Btn onClick={()=>setS(p=>({...p,bill:{...p.bill,rebels:clamp(p.bill.rebels-8,0,100),controversy:clamp(p.bill.controversy+4,0,100)},unity:clamp(p.unity-4,0,100),headline:'Three-line whip imposed'}))}>Hard three-line whip</Btn><Btn onClick={()=>setS(p=>({...p,bill:{...p.bill,controversy:clamp(p.bill.controversy-5,0,100),amends:[...p.bill.amends,'Committee evidence']},headline:'Select Committee evidence improves bill'}))}>Send ministers to committee</Btn><Btn onClick={()=>setS(p=>({...p,bill:{...p.bill,stage:clamp(p.bill.stage+1,0,8)},headline:`${p.bill.name} advances to next stage`,phase:p.bill.stage>=8?'government':'bill'}))}>Advance Stage</Btn></div>{b.amends.length>0&&<p className="log">Tactics used: {b.amends.join(', ')}</p>}</>}

function Cobra({s,setS}){const c=s.cobra;return <><Section kicker="COBRA Emergency Room" title={c.title} sub={`Threat level: ${c.threat}`}/><div className="advice">{c.advice.map(a=><p key={a}>{a}</p>)}</div><div className="actions">{c.opts.map((o,i)=><Btn key={o} onClick={()=>setS(p=>({...p,phase:'government',approval:clamp(p.approval+(i===3?-5:3),5,80),leadership:clamp(p.leadership+(i===3?10:-4),0,100),headline:`COBRA response: ${o}`,log:[`COBRA decision: ${o}`,...p.log]}))}>{o}</Btn>)}</div></>}
function ByElection({s,setS}){const b=s.byelection;return <><Section kicker="By-election" title={b.name} sub={`${b.nation} seat under pressure after recall petition.`}/><div className="miniRow"><Stat k="Electorate" v={b.electorate.toLocaleString()}/><Stat k="Pressure" v="64%"/><Stat k="Type" v={b.nation}/></div><div className="actions">{['Send the PM','Deploy star minister','Local spending promise','Attack campaign','Target local issue','Ignore seat'].map((o,i)=><Btn key={o} onClick={()=>setS(p=>({...p,phase:'government',approval:clamp(p.approval+(i===5?-4:2),5,80),leadership:clamp(p.leadership+(i===5?9:-3),0,100),headline:`By-election result: ${i===5?'Opposition gain':'Government hold'}`,log:[`${b.name}: ${i===5?'lost':'held'} after ${o}.`,...p.log]}))}>{o}</Btn>)}</div></>}
function Summit({s,setS}){const sm=s.summit;return <><Section kicker="Global Summit" title={sm.title} sub="High-stakes international negotiations with world leaders."/><div className="chips">{sm.leaders.map(l=><span key={l}>{l}</span>)}</div><div className="actions">{sm.opts.map((o,i)=><Btn key={o} onClick={()=>setS(p=>({...p,phase:'government',market:clamp(p.market+(i===0?-2:4),0,100),approval:clamp(p.approval+(i===2?1:2),5,80),headline:`${sm.title}: ${o}`,log:[`Summit decision: ${o}`,...p.log]}))}>{o}</Btn>)}</div></>}
function MapExplorer({s,setS}){const [q,setQ]=useState('');const filtered=seats.filter(x=>x.name.toLowerCase().includes(q.toLowerCase())).slice(0,60);const [sel,setSel]=useState(seats[0]);return <><Section kicker="Election HQ" title="Interactive UK Constituency Map" sub="Search, click and target constituencies across all 650 seats."/><div className="mapTools"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search constituency..."/></div><div className="mapWrap"><div className="map">{seats.slice(0,220).map((seat,i)=><button key={i} onClick={()=>setSel(seat)} style={{left:`${seat.x}%`,top:`${seat.y}%`}} className={seat.nation==='Scotland'?'sco':seat.nation==='Wales'?'wal':seat.nation==='Northern Ireland'?'ni':'eng'} title={seat.name}/>)}</div><div className="seatCard"><h3>{sel.name}</h3><p>{sel.nation}</p><Stat k="Electorate" v={sel.electorate.toLocaleString()}/><div className="actions small"><Btn onClick={()=>setS(p=>({...p,headline:`NHS campaign launched in ${sel.name}`}))}>NHS Push</Btn><Btn onClick={()=>setS(p=>({...p,headline:`Economy campaign launched in ${sel.name}`}))}>Economy Push</Btn></div><div className="results">{filtered.map(x=><button key={x.name} onClick={()=>setSel(x)}>{x.name}</button>)}</div></div></div></>}

function Opposition({s}){const opp=s.party.short==='Labour'?'Conservative':'Labour';return <div className="opposition"><h3>Opposition Watch: {opp}</h3><div className="chips">{(opponents[opp]||opponents.Labour).map(x=><span key={x}>{x}</span>)}</div></div>}
function Ticker({s,polling,projected}){const items=[`BBC POLITICS · ${s.headline}`,`OPPOSITION · ${(opponents[s.party.short==='Labour'?'Conservative':'Labour']||[])[1]} attacks government strategy`,`FT MARKETS · Inflation at ${s.inflation}%`,`POLL · ${s.party.short} projected on ${s.seats||projected} seats, polling ${polling}%`,`SOCIAL · ${s.social[0]}`];return <div className="ticker"><b>LIVE NEWS</b><div>{[...items,...items].map((x,i)=><span key={i}>{x}</span>)}</div></div>}
function Panel({title,children}){return <div className="panel"><h2>{title}</h2>{children}</div>}
function Card({title,children}){return <div className="card"><h2>{title}</h2>{children}</div>}
function Stat({k,v}){return <div className="stat"><small>{k}</small><b>{v}</b></div>}
function Section({kicker,title,sub}){return <div className="section"><small>{kicker}</small><h2>{title}</h2><p>{sub}</p></div>}
function Btn({children,onClick}){return <button className="btn" onClick={onClick}>{children}</button>}
